name: flutter_screen_generator
description: A simple flutter screen generator package.
version: 0.0.5
homepage: https://github.com/ahmedelmwafy/flutter_screen_generator

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  yaml: ^3.1.3
  path: ^1.9.1

executables:
  flutter_screen_generator: flutter_screen_generator
